version: '3.0'

services:
  neo4j:
    image: neo4j:latest
    ports: 
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - /Users/vikasvig/Desktop/mp3:/var/lib/neo4j/import  # Default import directory
    environment:
      NEO4J_AUTH: 'neo4j/password' # username/password
      NEO4J_PLUGINS: '["graph-data-science"]' # importing plugins